[workspace]
resolver = "2"
members = [
    "cac",
    "cct",
    "ext",
    "ds",
    "dsig_11",
    "xades",
    "udt",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", features = ["serde"] }
thiserror = "2"
