[workspace]
resolver = "2"
members = [
    "ubl-common",
    "ubl-documents",
    "ubl-xml",
    "peppol-common",
    "peppol-billing",
    "peppol-ordering",
    "peppol-despatch",
]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
rust_decimal = { version = "1", features = ["serde"] }
