pub struct ApplicationResponse {
    ubl_extensions: Option<ext::UblExtensions>,
    ubl_version_id: Option<cbc::UblVersionId>,
    customization_id: Option<cbc::CustomizationId>,
    profile_id: Option<cbc::ProfileId>,
    profile_execution_id: Option<cbc::ProfileExecutionId>,
    id: cbc::Id,
    uuid: Option<cbc::Uuid>,
    issue_date: Option<cbc::IssueDate>,
    issue_time: Option<cbc::IssueTime>,
    response_date: Option<cbc::ResponseDate>,
    response_time: Option<cbc::ResponseTime>,
    notes: Vec<cbc::Note>,
    version_id: Option<cbc::VersionId>,
    signatures: Vec<cac::Signature>,
    sender_party: cac::SenderParty,
    receiver_party: cac::ReceiverParty,
    document_responses: Vec<cac::DocumentResponse>,
}
