#[derive(Debug, Deserialize, Serialize)]
/// A class to describe circular economy-related properties of a product, including its resource
/// efficiency, reusability, repairability, and end-of-life treatment.
///
/// UBL Dictionary Entry Name: `Circularity Profile. Details`
///
/// Generated from XSD type `CircularityProfileType`.
pub struct CircularityProfile {
/// A container for extensions foreign to the document.
    #[serde(default, rename = "UBLExtensions")]
    pub ubl_extensions:
        Option<ext::UblExtensions>,
/// A code indicating the type of circularity applicable to the profiled entity.
    #[serde(default, rename = "CircularityTypeCode")]
    pub circularity_type_code: Option<cct::Code>,
/// The percentage of recycled material in the profiled entity.
    #[serde(default, rename = "RecycledContentPercent")]
    pub recycled_content_percent: Option<cct::Numeric>,
/// The percentage of the product or material that can be recycled.
    #[serde(default, rename = "RecyclabilityPercent")]
    pub recyclability_percent: Option<cct::Numeric>,
/// A code specifying the recommended frequency for routine maintenance.
    #[serde(default, rename = "MaintenanceFrequencyCode")]
    pub maintenance_frequency_code: Option<cct::Code>,
/// A text describing the recommended frequency for routine maintenance.
    #[serde(default, rename = "MaintenanceFrequencyDescription")]
    pub maintenance_frequency_description: Vec<cct::Text>,
/// A record of a resource consumed, such as energy, water, or materials.
    #[serde(default, rename = "ResourceConsumption")]
    pub resource_consumption: Vec<ResourceConsumption>,
/// The waste generated by the profiled entity.
    #[serde(default, rename = "WasteGenerated")]
    pub waste_generated: Vec<WasteGenerated>,
/// An assigned Score indicating the ease of repair of the product.
    #[serde(default, rename = "RepairabilityScore")]
    pub repairability_score: Vec<Score>,
/// Information about how the profiled entity is expected to be treated at the end of its lifecycle
    #[serde(default, rename = "EndOfLifeTreatment")]
    pub end_of_life_treatment: Option<EndOfLifeTreatment>,
/// One or more product documentations such as repair instructions, sustainability disclosures,
/// circularity declarations, or technical manuals.
    #[serde(default, rename = "ProductDocumentationDocumentReference")]
    pub product_documentation_document_reference: Vec<DocumentReference>,
}
