#![allow(unused_imports, dead_code, non_snake_case, clippy::all)]
use serde::{Deserialize, Serialize};

pub mod activity;
pub use activity::*;
pub mod address;
pub use address::*;
pub mod attestation;
pub use attestation::*;
pub mod awarding;
pub use awarding::*;
pub mod ballast_water;
pub use ballast_water::*;
pub mod billing_reference;
pub use billing_reference::*;
pub mod budget;
pub use budget::*;
pub mod catalogue;
pub use catalogue::*;
pub mod certificate;
pub use certificate::*;
pub mod classification;
pub use classification::*;
pub mod consumption;
pub use consumption::*;
pub mod contract;
pub use contract::*;
pub mod contracting;
pub use contracting::*;
pub mod credit;
pub use credit::*;
pub mod delivery;
pub use delivery::*;
pub mod despatch;
pub use despatch::*;
pub mod digital;
pub use digital::*;
pub mod document;
pub use document::*;
pub mod economic;
pub use economic::*;
pub mod encryption;
pub use encryption::*;
pub mod energy;
pub use energy::*;
pub mod event;
pub use event::*;
pub mod evidence;
pub use evidence::*;
pub mod exception;
pub use exception::*;
pub mod financial;
pub use financial::*;
pub mod forecast;
pub use forecast::*;
pub mod fuel;
pub use fuel::*;
pub mod goods;
pub use goods::*;
pub mod hazardous;
pub use hazardous::*;
pub mod item;
pub use item::*;
pub mod line;
pub use line::*;
pub mod location;
pub use location::*;
pub mod lot;
pub use lot::*;
pub mod maritime;
pub use maritime::*;
pub mod meter;
pub use meter::*;
pub mod order;
pub use order::*;
pub mod party;
pub use party::*;
pub mod payment;
pub use payment::*;
pub mod port;
pub use port::*;
pub mod price;
pub use price::*;
pub mod procurement;
pub use procurement::*;
pub mod promotional;
pub use promotional::*;
pub mod purchase;
pub use purchase::*;
pub mod radioactive;
pub use radioactive::*;
pub mod request;
pub use request::*;
pub mod response;
pub use response::*;
pub mod security;
pub use security::*;
pub mod service;
pub use service::*;
pub mod ship;
pub use ship::*;
pub mod shipment;
pub use shipment::*;
pub mod supplier;
pub use supplier::*;
pub mod tax;
pub use tax::*;
pub mod telecommunications;
pub use telecommunications::*;
pub mod tender;
pub use tender::*;
pub mod tenderer;
pub use tenderer::*;
pub mod tendering;
pub use tendering::*;
pub mod transport;
pub use transport::*;
pub mod transportation;
pub use transportation::*;
pub mod web;
pub use web::*;
pub mod work;
pub use work::*;

include!("air_transport.rs");
include!("allowance_charge.rs");
include!("annotation.rs");
include!("appeal_terms.rs");
include!("attachment.rs");
include!("auction_terms.rs");
include!("authorization.rs");
include!("branch.rs");
include!("buyer_assigned_reference.rs");
include!("capability.rs");
include!("card_account.rs");
include!("cash_register.rs");
include!("circularity_profile.rs");
include!("clause.rs");
include!("commodity_classification.rs");
include!("communication.rs");
include!("completed_task.rs");
include!("condition.rs");
include!("consignment.rs");
include!("contact.rs");
include!("corporate_registration_scheme.rs");
include!("country.rs");
include!("crew_person_effect.rs");
include!("criterion_item.rs");
include!("customer_party.rs");
include!("customs_declaration.rs");
include!("debit_note_line.rs");
include!("declaration.rs");
include!("dependent_price_reference.rs");
include!("dimension.rs");
include!("duty.rs");
include!("electronic_address.rs");
include!("emission_calculation_method.rs");
include!("end_of_life_treatment.rs");
include!("endorsement.rs");
include!("endorser_party.rs");
include!("environmental_emission.rs");
include!("evaluation_criterion.rs");
include!("exchange_rate.rs");
include!("external_reference.rs");
include!("fee.rs");
include!("framework_agreement.rs");
include!("immobilized_security.rs");
include!("instruction_for_returns_line.rs");
include!("insurance_policy.rs");
include!("interest_rate.rs");
include!("inventory_report_line.rs");
include!("invoice_line.rs");
include!("isps_requirements.rs");
include!("language.rs");
include!("legislation.rs");
include!("lots_group.rs");
include!("message_delivery.rs");
include!("miscellaneous_event.rs");
include!("monetary_total.rs");
include!("notice_sub_type.rs");
include!("notification_requirement.rs");
include!("on_account_payment.rs");
include!("operation_type.rs");
include!("ordered_shipment.rs");
include!("package.rs");
include!("participant_party.rs");
include!("performance_data_line.rs");
include!("period.rs");
include!("person.rs");
include!("personnel_health_incident.rs");
include!("physical_attribute.rs");
include!("pickup.rs");
include!("post_award_process.rs");
include!("power_of_attorney.rs");
include!("pricing_reference.rs");
include!("prize.rs");
include!("process_justification.rs");
include!("project_reference.rs");
include!("property_identification.rs");
include!("qualification_resolution.rs");
include!("qualifying_party.rs");
include!("quotation_line.rs");
include!("rail_transport.rs");
include!("receipt_line.rs");
include!("regulation.rs");
include!("related_item.rs");
include!("reminder_line.rs");
include!("remittance_advice_line.rs");
include!("renewal.rs");
include!("requested_tender_total.rs");
include!("resource_consumption.rs");
include!("result_of_verification.rs");
include!("retail_planned_impact.rs");
include!("road_transport.rs");
include!("sales_item.rs");
include!("sanitary_measure.rs");
include!("score.rs");
include!("secondary_hazard.rs");
include!("shareholder_party.rs");
include!("signature.rs");
include!("social_media_profile.rs");
include!("statement_line.rs");
include!("status.rs");
include!("stock_availability_report_line.rs");
include!("storage.rs");
include!("stowage.rs");
include!("subcontract_terms.rs");
include!("subscriber_consumption.rs");
include!("temperature.rs");
include!("tendered_project.rs");
include!("trade_financing.rs");
include!("trading_terms.rs");
include!("transaction_conditions.rs");
include!("unstructured_price.rs");
include!("utility_item.rs");
include!("verified_gross_mass.rs");
include!("vessel_dynamics.rs");
include!("waste_generated.rs");
include!("who_affected_area_visit.rs");
include!("winning_party.rs");
