#[derive(Debug, Deserialize, Serialize)]
/// A class to describe a quantity of waste generated by an item, process, or activity, including type,
/// quantity, and optional lifecycle context.
///
/// UBL Dictionary Entry Name: `Waste Generated. Details`
///
/// Generated from XSD type `WasteGeneratedType`.
pub struct WasteGenerated {
/// A container for extensions foreign to the document.
    #[serde(default, rename = "UBLExtensions")]
    pub ubl_extensions: Option<ext::UblExtensions>,
/// A code identifying the type of waste generated.
    #[serde(default, rename = "WasteTypeCode")]
    pub waste_type_code: Option<cct::Code>,
/// A text describing the type of waste generated.
    #[serde(default, rename = "WasteTypeDescription")]
    pub waste_type_description: Vec<cct::Text>,
/// A measurement of the amount of waste generated.
    #[serde(rename = "WasteMeasure")]
    pub waste_measure: cct::Measure,
/// The period during which this waste was generated or measured.
    #[serde(default, rename = "MeasurementPeriod")]
    pub measurement_period: Option<Period>,
}
