#![allow(unused_imports, dead_code, non_snake_case, clippy::all)]
use serde::{Deserialize, Serialize};
use std::num::NonZeroUsize;
include!("char_two_field_params_type.rs");
include!("curve_type.rs");
include!("der_encoded_key_value.rs");
include!("ec_key_value.rs");
include!("ec_key_value_type_content.rs");
include!("ec_parameters_type.rs");
include!("ec_point_type.rs");
include!("ec_validation_data_type.rs");
include!("field_id_type.rs");
include!("gn_b.rs");
include!("key_info_reference.rs");
include!("named_curve_type.rs");
include!("pn_b.rs");
include!("pn_b_field_params_type.rs");
include!("prime.rs");
include!("prime_field_params_type.rs");
include!("tn_b.rs");
include!("tn_b_field_params_type.rs");
include!("x509_digest.rs");
